### PR TITLE
ROCANA-3510 Impala's Hive from HDP does not have hive_metastore.thrift

### PR DESCRIPTION
**Pull request by bradcupit**
See commit comment for details.

The only files changed in this PR are under `thirdparty/hive-1.2.1.2.3.0.0-2557/src/`. These files were originally missing from Hortonwork's Hive tarball. We added them to the local file system used to do compiles, but since `thirdparty/` is in .gitignore I never added them to git. Oops.

### CODE REVIEW

**Comment by joey** [comment]
So the source and binaries are required?

**Comment by bradcupit** [comment]
Good question. I know `src/metastore/if/hive_metastore.thrift` is required.

The old `hive-1.1.0-cdh5.4.5` had the entire `src` folder, including `src/metastore/if/hive_metastore.thrift`. The new Hive from HDP did not have the `src` folder at all, so I added the whole thing to new Hive.

I'll try a test to see if we only need the `src/metastore/if/hive_metastore.thrift` and therefore can keep only it.

**Comment by joey** [comment]
If the CDH version had it, I'd be inclined to keep it. The CDH version also had the compiled jars, yes?

**Comment by bradcupit** [comment]
Yes, both CDH and upstream Apache Hive have the `src` folder.

Which folder are you looking in for the compiled jars? I can't find them.

**Comment by joey** [comment]
```
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/jul-to-slf4j-1.7.5.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/hive-webhcat-1.2.1.2.3.0.0-2557.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/jersey-server-1.14.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/jackson-jaxrs-1.9.2.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/jettison-1.1.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/asm-3.1.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/jackson-xc-1.9.2.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/jersey-json-1.14.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/jackson-core-asl-1.9.2.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/jaxb-api-2.2.2.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/jaxb-impl-2.2.3-1.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/xml-apis-1.3.04.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/commons-exec-1.1.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/jersey-core-1.14.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/stax-api-1.0-2.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/xercesImpl-2.9.1.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/wadl-resourcedoc-doclet-1.4.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/svr/lib/jersey-servlet-1.14.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/webhcat/java-client/hive-webhcat-java-client-1.2.1.2.3.0.0-2557.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/hcatalog/hive-hcatalog-core-1.2.1.2.3.0.0-2557.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/hcatalog/hive-hcatalog-server-extensions-1.2.1.2.3.0.0-2557.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/hcatalog/hive-hcatalog-streaming-1.2.1.2.3.0.0-2557.jar
hive-1.2.1.2.3.0.0-2557/hcatalog/share/hcatalog/hive-hcatalog-pig-adapter-1.2.1.2.3.0.0-2557.jar
hive-1.2.1.2.3.0.0-2557/lib/hive-jdbc-1.2.1.2.3.0.0-2557-standalone.jar
hive-1.2.1.2.3.0.0-2557/lib/maven-scm-provider-svn-commons-1.4.jar
hive-1.2.1.2.3.0.0-2557/lib/htrace-core-3.1.0-incubating.jar
hive-1.2.1.2.3.0.0-2557/lib/hive-cli-1.2.1.2.3.0.0-2557.jar
hive-1.2.1.2.3.0.0-2557/lib/jdo-api-3.0.1.jar
hive-1.2.1.2.3.0.0-2557/lib/accumulo-start-1.7.0.2.3.0.0-2557.jar
hive-1.2.1.2.3.0.0-2557/lib/commons-codec-1.4.jar
hive-1.2.1.2.3.0.0-2557/lib/guava-14.0.1.jar
hive-1.2.1.2.3.0.0-2557/lib/plexus-utils-1.5.6.jar
...
```

**Comment by joey** [comment]
I checked the CDH version, and it also has the jars and the source.

+1

**Pull request merged**
